Added pagination for load photos
Simple2B/Pollock pull request #30
Opened 2021-08-30 11:20 UTC by SvyatoslavArtymyvych

2021-08-30 17:59 UTC, varvarashcherbyna7 approved these changes

2021-08-30 22:11 UTC, kipod requested changes
thank you.
please see my comments

2021-08-30 22:11 UTC, kipod commented on app/views/photo_contest.py
> +            )
```python
photo_list = [(photo.file_name, photo.id, url_for("main.image", path=(photo.file_name)), "on" if has_liked_photo(user=current_user, photo=photo) else "off") for photo in paginated_photos]
```

2021-08-30 22:11 UTC, kipod commented on app/views/photo_contest.py
> +            )
one line vs. 15 lines =)

2021-08-30 22:11 UTC, kipod commented on app/views/photo_contest.py
>              res = make_response(jsonify({}), 200)
```python
res = make_response(jsonify([]), 200)
```
returns array, not object

2021-08-30 22:11 UTC, kipod commented on app/views/photo_contest.py
> +from math import ceil
import of standard module must be before all others!

2021-08-31 08:31 UTC, varvarashcherbyna7 commented on app/views/photo_contest.py
>              res = make_response(jsonify({}), 200)
it seems to me that it should return object in which there is data with an array

2021-09-01 16:45 UTC, closed without merging